const $=id=>document.getElementById(id);let rows=[];
$('csv').addEventListener('change',e=>readCSV(e.target.files[0]));$('shot').addEventListener('change',e=>{if(e.target.files[0])$('signalText').textContent='Screenshot attached. CSV data remains the primary numerical source.'});
$('horizon').addEventListener('change',e=>$('horizonOut').textContent=e.target.value);
['dragenter','dragover'].forEach(x=>$('drop').addEventListener(x,e=>{e.preventDefault();$('drop').style.borderColor='#a9ff6b'}));$('drop').addEventListener('drop',e=>{e.preventDefault();readCSV(e.dataTransfer.files[0])});
function readCSV(file){if(!file)return;if(!file.name.toLowerCase().endsWith('.csv'))return alert('Please choose a CSV file.');const r=new FileReader();r.onload=()=>{rows=parseCSV(r.result);if(rows.length<10)return alert('Need at least 10 OHLCV rows.');render(rows)};r.readAsText(file)}
function parseCSV(t){const a=t.trim().split(/\r?\n/).map(x=>x.split(','));const h=a.shift().map(x=>x.trim().toLowerCase());const ci=h.findIndex(x=>x==='close'||x==='closing price');const ti=h.findIndex(x=>x.includes('time')||x.includes('date'));return a.map(x=>({date:ti>=0?x[ti]:'',close:Number(x[ci])})).filter(x=>Number.isFinite(x.close))}
function render(d){$('symbol').textContent=(d[0].ticker||'MARKET')+' • 1D';const last=d.at(-1).close;$('last').textContent=fmt(last);const n=+($('horizon').value.match(/\d+/)||[5])[0];const recent=d.slice(-80);const vals=recent.map(x=>x.close);const trend=(vals.at(-1)-vals[0])/Math.max(1,vals[0]);const dir=trend>=0?'UP':'DOWN';$('direction').textContent=dir;$('direction').style.color=dir==='UP'?'#a9ff6b':'#ff8f8f';$('confidence').textContent=Math.round(Math.min(96,52+Math.abs(trend)*700))+'% trend confidence';$('signalText').textContent='Baseline projection is generated locally. Connect the original Kronos runtime later for true model inference.';$('end').textContent=fmt(last*(1+trend/n));draw(vals,n);backtest(vals)}
function draw(vals,n){const c=$('chart'),x=c.getContext('2d'),dpr=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*dpr;c.height=h*dpr;x.scale(dpr,dpr);x.clearRect(0,0,w,h);let all=vals.slice(),step=(vals.at(-1)-vals[Math.max(0,vals.length-10)])/10;for(let i=1;i<=n;i++)all.push(vals.at(-1)+step*i);const mn=Math.min(...all),mx=Math.max(...all),pad=30;const X=i=>pad+i*(w-pad*2)/(all.length-1),Y=v=>h-pad-(v-mn)/(mx-mn||1)*(h-pad*2);x.strokeStyle='#202733';x.lineWidth=1;for(let i=0;i<5;i++){let yy=pad+i*(h-pad*2)/4;x.beginPath();x.moveTo(pad,yy);x.lineTo(w-pad,yy);x.stroke()}x.lineWidth=2;x.beginPath();vals.forEach((v,i)=>{i?x.lineTo(X(i),Y(v)):x.moveTo(X(i),Y(v))});x.strokeStyle='#e9edf3';x.stroke();x.setLineDash([5,5]);x.beginPath();for(let i=vals.length-1;i<all.length;i++){i===vals.length-1?x.moveTo(X(i),Y(all[i])):x.lineTo(X(i),Y(all[i]))}x.strokeStyle='#a9ff6b';x.stroke();x.setLineDash([])}
function backtest(v){const base=v.slice(1).map((_,i)=>v[i]);const actual=v.slice(1);let mae=0,rmse=0,correct=0;for(let i=0;i<actual.length;i++){let e=actual[i]-base[i];mae+=Math.abs(e);rmse+=e*e;if(i>0&&Math.sign(actual[i]-actual[i-1])===Math.sign(base[i]-v[i]))correct++}mae/=actual.length;rmse=Math.sqrt(rmse/actual.length);const dir=correct/Math.max(1,actual.length-1)*100;$('mae').textContent=fmt(mae);$('rmse').textContent=fmt(rmse);$('dir').textContent=Math.round(dir)+'%';$('maeBar').style.width='62%';$('rmseBar').style.width='70%';$('dirBar').style.width=Math.min(100,dir)+'%'}
function fmt(n){return Number(n).toLocaleString(undefined,{maximumFractionDigits:2})}
function loadDemo(){const d=[];let p=2850;for(let i=0;i<120;i++){p*=1+(Math.sin(i/8)*.004)+(Math.random()-.48)*.012;d.push({date:'D'+i,close:p})}rows=d;render(d)}
window.addEventListener('resize',()=>{if(rows.length)render(rows)});